const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const data = (file, mime) => `data:${mime};base64,${fs.readFileSync(path.join(root, file)).toString('base64')}`;
const sticker = name => data(`public/assets/stickers/${name}.png`, 'image/png');
const fonts = [400,600].map(weight => `@font-face{font-family:Plex;src:url("${data(`node_modules/@fontsource/ibm-plex-sans/files/ibm-plex-sans-latin-${weight}-normal.woff2`,'font/woff2')}") format('woff2');font-weight:${weight};font-display:swap}@font-face{font-family:PlexThai;src:url("${data(`node_modules/@fontsource/ibm-plex-sans-thai/files/ibm-plex-sans-thai-thai-${weight}-normal.woff2`,'font/woff2')}") format('woff2');font-weight:${weight};font-display:swap}`).join('');
const css = `${fonts}
*{box-sizing:border-box}html{color-scheme:light}body{margin:0;color:#280d5a;font-family:Plex,PlexThai,Arial,sans-serif;background:#fff}a{color:inherit}img{display:block;max-width:100%}
.hero{max-width:1120px;margin:auto;padding:40px 48px;border:1px solid #e9e3fb;border-radius:28px;background:radial-gradient(ellipse at 95% 5%,#e3d5ff 0,transparent 50%),linear-gradient(135deg,#fff,#f4f2fb);display:grid;grid-template-columns:1.35fr 1fr;gap:24px;align-items:center}
.eyebrow{display:inline-block;background:#280d5a;color:white;border-radius:30px;padding:8px 16px;font-size:12px;letter-spacing:2px;font-weight:600}
h1{font-size:clamp(32px,5.5vw,62px);line-height:1.06;letter-spacing:-2px;margin:24px 0 0;font-weight:600}h1 span{display:block}.country{color:#c81264;margin-top:8px}.accent{height:5px;width:80px;background:linear-gradient(90deg,#f86dad,#b796f6);border-radius:8px;margin:22px 0}.intro{font-size:17px;line-height:1.7;margin:0}.meta{display:flex;flex-wrap:wrap;gap:8px;margin-top:18px}.meta span{font-size:12px;padding:5px 10px;border:1px solid #d6c6fc;border-radius:20px;background:#ffffffb3}
.art{position:relative;min-width:0;width:100%;max-width:360px;aspect-ratio:1;justify-self:center}.art img{position:absolute;object-fit:contain}.eagle{width:72%;right:0;top:0;transform:rotate(-7deg)}.bluebird{width:37%;left:0;top:6%;transform:rotate(-10deg)}.hummingbirds{width:42%;left:0;bottom:9%;transform:rotate(8deg)}.badge{width:43%;right:1%;bottom:0;transform:rotate(12deg)}
.preview{padding:28px 20px 40px;background:#f4f2fb;min-height:100vh}.topline{max-width:1120px;margin:0 auto 18px;display:flex;justify-content:space-between;align-items:center;font-size:12px;letter-spacing:1px;gap:16px}.topline a{text-decoration:none}.form-area{max-width:760px;margin:28px auto 0;background:white;border:1px solid #e1d8f0;border-top:6px solid #461d8a;border-radius:18px;padding:32px}.form-area h2{font-size:28px;line-height:1.3;margin:0 0 12px}.form-area p{font-size:16px;line-height:1.8;margin:0}.placeholder{margin-top:22px;border:1px dashed #b796f6;border-radius:12px;padding:28px 18px;background:#faf9ff;text-align:center;color:#6e5b99}.placeholder strong{display:block;margin-bottom:8px;color:#280d5a}.footer{text-align:center;font-size:12px;line-height:1.8;margin:24px 0 0;color:#6e5b99}
@media(max-width:600px){.hero{padding:26px 22px;grid-template-columns:1fr;gap:12px;border-radius:20px}h1{font-size:38px;letter-spacing:-1px;margin-top:18px}.intro{font-size:15px}.accent{margin:18px 0}.art{width:190px}.eyebrow{font-size:10px}.meta{margin-top:14px}.preview{padding:16px 12px 28px}.form-area{padding:24px 20px;margin-top:20px}.form-area h2{font-size:25px}.topline{font-size:10px}}
`;
const hero = `<section class="hero" aria-label="Qiskit Fall Fest 2026 Thailand"><div><div class="eyebrow">QTRiC · THAILAND</div><h1><span>Qiskit Fall Fest</span><span>2026</span><span class="country">Thailand</span></h1><div class="accent"></div><p class="intro">Explore quantum computing. Learn by doing.</p><div class="meta"><span>Free registration</span><span>Online + On-site Workshops</span></div></div><div class="art" aria-hidden="true"><img class="eagle" src="${sticker('eagle')}" alt=""><img class="bluebird" src="${sticker('bluebird')}" alt=""><img class="hummingbirds" src="${sticker('hummingbirds')}" alt=""><img class="badge" src="${sticker('badge')}" alt=""></div></section>`;
const document = body => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Qiskit Fall Fest 2026 · Registration</title><style>${css}</style></head><body>${body}</body></html>`;
fs.writeFileSync(path.join(__dirname,'header-embed.html'),document(hero));
fs.writeFileSync(path.join(__dirname,'preview.html'),document(`<main class="preview"><nav class="topline"><span>QTRiC / QISKIT FALL FEST 2026</span><a href="https://qtric.sut.ac.th/qff2026/" target="_blank" rel="noopener">Main website ↗</a></nav>${hero}<section class="form-area"><h2>Register for the event</h2><p>Register for Qiskit Fall Fest 2026: Thailand</p><div class="placeholder"><strong>Your Google Form goes here</strong>Layout preview — registration form not connected yet.<br>Insert your Google Form below the banner in Google Sites.</div></section><p class="footer">QTRiC · Qiskit Fall Fest 2026 Thailand<br>A decade of quantum on the cloud</p></main>`));
console.log('Created header-embed.html and preview.html');
